name: Louis Oliver
favicon: null
layout_spectrum: 0.19877
typography_spectrum: 0.51373
title: Louis Oliver
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2c2c2c'
    - '#a5c5d4'
    - '#a49993'
    - '#ecec94'
    - '#625648'
  brandStrength: 0.3125
  lightness: 0.125
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
