name: Louis Oliver
favicon: null
layout_spectrum: 0.10265
typography_spectrum: 0.51373
title: Louis Oliver
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#22222a'
    - '#f8f8f8'
    - '#5c312b'
    - '#9d683e'
    - '#c9832c'
  brandStrength: 0.3125
  lightness: 0.125
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
